Repository cloudevents/sdk-rust, pull requests merged in 2020-11, with the labels that each got.

#95 Another round of docs fix + cleanups
  Cargo.toml
  README.md
  cloudevents-sdk-actix-web/Cargo.toml
  cloudevents-sdk-actix-web/src/lib.rs
  cloudevents-sdk-actix-web/src/server_request.rs
  cloudevents-sdk-actix-web/src/server_response.rs
  cloudevents-sdk-actix-web/tests/version_number.rs
  cloudevents-sdk-rdkafka/Cargo.toml
  cloudevents-sdk-rdkafka/src/kafka_consumer_record.rs
  cloudevents-sdk-rdkafka/src/kafka_producer_record.rs
  cloudevents-sdk-rdkafka/src/lib.rs
  cloudevents-sdk-rdkafka/tests/version_number.rs
  cloudevents-sdk-reqwest/Cargo.toml
  cloudevents-sdk-reqwest/src/client_request.rs
  cloudevents-sdk-reqwest/src/client_response.rs
  cloudevents-sdk-reqwest/src/lib.rs
  cloudevents-sdk-reqwest/tests/version_number.rs
  example-projects/actix-web-example/Cargo.toml
  example-projects/actix-web-example/src/main.rs
  example-projects/rdkafka-example/Cargo.toml
  example-projects/rdkafka-example/src/main.rs
  src/event/attributes.rs
  src/event/data.rs
  src/event/extensions.rs
  src/event/mod.rs
  src/event/spec_version.rs
  src/lib.rs
  src/message/deserializer.rs
  src/message/encoding.rs
  src/message/mod.rs
  src/message/serializer.rs
  src/message/types.rs
  tests/version_number.rs
Labels: dependencies, documentation, enhancement

#96 CI Improvements
  .github/workflows/pr.yml
  .github/workflows/pull_requests_lints.yml
  .github/workflows/rust_tests.yml
  cloudevents-sdk-rdkafka/Cargo.toml
  example-projects/rdkafka-example/Cargo.toml
Labels: enhancement

#102 Remove actix_rt dependency in actix_web example
  example-projects/actix-web-example/Cargo.toml
  example-projects/actix-web-example/src/main.rs
Labels: documentation, enhancement

#103 Change unused dependency to dev_dependency
  cloudevents-sdk-actix-web/Cargo.toml
Labels: documentation, enhancement

#100 Fix lint warnings
  cloudevents-sdk-actix-web/src/server_request.rs
  cloudevents-sdk-rdkafka/src/headers.rs
  cloudevents-sdk-rdkafka/src/kafka_consumer_record.rs
  cloudevents-sdk-rdkafka/src/kafka_producer_record.rs
  cloudevents-sdk-reqwest/src/client_response.rs
  src/event/attributes.rs
  src/event/event.rs
  src/event/format.rs
  src/event/mod.rs
  src/event/spec_version.rs
  src/event/v03/attributes.rs
  src/event/v03/format.rs
  src/event/v10/attributes.rs
  src/event/v10/format.rs
  src/message/deserializer.rs
Labels: enhancement

#101 Fix typo
  README.md
Labels: bug, documentation
